title = "Simon Perche"
baseURL = "https://simonperche.github.io"
theme = "resume"
languageCode = "fr-fr"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Lyon, France"
email = "simon.perche@liris.cnrs.fr"
favicon = ""
firstName = "Simon"
lastName = "Perche"
#phone = "1-555-555-1234"
profileImage = "img/photo.jpg"
showEducation = true
showExperience = true
showOpenSource = false
showProjects = false
showPublications = true
showQr = false
showSkills = false

#[params.google]

#[params.google.analytics]
#trackerID = "XX-123446-01"


[[params.handles]]
link = "https://drive.google.com/file/d/1ja1so6hBTipcb_S6GlbR-tgE4Amxf2KB/view?usp=sharing"
name = "Resume"
icon = "id-card"

[[params.handles]]
link = "https://arches.liris.cnrs.fr"
name = "Arches team"
icon = "archway"

[[params.handles]]
link = "https://projet.liris.cnrs.fr/ampli/"
name = "Ampli project"
icon = "mountain"

[[params.handles]]
link = "https://www.linkedin.com/in/simon-perche/"
name = "LinkedIn"
isbrand = true

[[params.handles]]
link = "https://github.com/SimonPerche"
name = "GitHub"
isbrand = true

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"